export const USERS_REQUEST_API_DATA = "USERS_REQUEST_API_DATA";
export const USERS_RECEIVE_API_DATA = "USERS_RECEIVE_API_DATA";
export const USERS_AGAIN_REQUEST_API_DATA = "USERS_AGAIN_REQUEST_API_DATA";
export const USERS_AGAIN_RECEIVE_API_DATA = "USERS_AGAIN_RECEIVE_API_DATA";
export const MODAL_OPEN = 'MODAL_OPEN';
export const MODAL_CLOSE = 'MODAL_CLOSE';
export const SHOW_NEXT = 'SHOW_NEXT';